name: Create PR to dev
on:
  workflow_call:
jobs:
  create_pr_to_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
      - name: Create PR to dev
        run: | 
          uvx --from github-rest-api@latest create_pull_request \
            --head-branch ${{ github.ref_name }} \
            --base-branch dev \
            --token ${{ secrets.ACTIONS_TOKEN }}

