name: Create PR From dev To main
on:
  workflow_call:
jobs:
  create_pr_dev_to_main:
    runs-on: ubuntu-latest
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
      - name: Create PR From dev To main
        run: | 
          uvx --from github-rest-api@latest create_pull_request \
            --head-branch dev \
            --base-branch main \
            --token ${{ secrets.ACTIONS_TOKEN }}

