name: Merge PR
on:
  workflow_call:
    inputs:
      dry_run:
        required: false
        type: boolean
        default: false
permissions:
  contents: write
  pull-requests: write
jobs:
  auto_merge_pull_request:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sudo env UV_INSTALL_DIR="/usr/local/bin" sh
      - name: Auto Merge PR
        run: |
          uvx --from github-rest-api@latest auto_merge_pull_request \
            --authors dclong \
            --approvers dclong 'claude[bot]' 'gemini-code-assist[bot]' \
            ${{ inputs.dry_run && '--dry-run' || '' }} \
            --token ${{ secrets.ACTIONS_TOKEN }}
